modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/Tslat/Passive-Mobs/issues"

[[mods]]
modId="passivemobs"
version="1.3.1"
displayName="Passive Mobs"
logoFile="logo.png"
authors="Tslat"
description="Everyone take a chill pill"

[[dependencies.passivemobs]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.passivemobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"