# Environment Settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Project Settings
# Your modId must be only lowercase letters, numbers, and _ or - symbols only
modDisplayName=PassiveMobs
modId=passivemobs
group=net.tslat

# Project Properties
modLicense=MIT
modAuthors=Tslat
modDescription=Everyone take a chill pill

# Links
modHomepage=https://www.curseforge.com/minecraft/mc-mods/passive-mobs
modGitRepo=https://github.com/Tslat/Passive-Mobs
modIssuesTracker=https://github.com/Tslat/Passive-Mobs/issues

# Publishing
modrinthProjectId=mjYxrwYd
curseforgeProjectId=469811