# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
group=net.tslat.passivemobs
modDisplayName=PassiveMobs
modId=passivemobs
modAuthors=Tslat
modDescription=Everyone take a chill pill
modLicense=MIT
modHomepageUrl=https://www.curseforge.com/minecraft/mc-mods/passive-mobs
modSourcesUrl=https://github.com/Tslat/Passive-Mobs
modIssuesUrl=https://github.com/Tslat/Passive-Mobs/issues

# Publishing
modCurseforgeId=469811
modModrinthId=mjYxrwYd
modChangelogUrl=https://github.com/Tslat/Passive-Mobs/commits/latest