modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPL3"

[[mods]]
modId="passivemobs"
version="1.2"
displayName="Passive Mobs"
logoFile="logo.png"
authors="Tslat"
description="Everyone take a chill pill"

[[dependencies.passivemobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
