modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
issueTrackerURL="https://github.com/Tslat/Passive-Mobs/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Passive Mobs"
logoFile="logo.png"
authors="Tslat"
description="Everyone take a chill pill"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
